SELECT ID,
CASE 
WHEN G.R = 1 THEN 'CRITICAL'
WHEN G.R = 2 THEN 'HIGH'
WHEN G.R = 3 THEN 'MEDIUM'
WHEN G.R = 4 THEN 'LOW'
END AS COLONY_NAME
FROM 
(SELECT ID,NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS R
FROM ECOLI_DATA) G
ORDER BY ID