SELECT FLAVOR
FROM (
  SELECT F.FLAVOR,
         (F.TOTAL_ORDER + J.JTOS) AS TTOS
  FROM FIRST_HALF AS F
  JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS JTOS
    FROM JULY
    GROUP BY FLAVOR
  ) AS J
  ON F.FLAVOR = J.FLAVOR
  ORDER BY TTOS DESC
  LIMIT 3
) AS T;
